CREATE TABLE qrtz_history
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL, 
    JOB_GROUP VARCHAR2(200) NOT NULL,
    START_TIME NUMBER(13) NOT NULL,
    END_TIME NUMBER(13) NOT NULL,
    IS_NORMAL NUMBER(1) NOT NULL,
    EXCEPTION_DESC VARCHAR2(2000) ,
    CONSTRAINT QRTZ_HISTORY_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,START_TIME)    
);
